spring.application.name=SWP391_SmokingCessationSupportPlatform

spring.datasource.url=${DBMS_CONNECTION:jdbc:mysql://localhost:3306/smoking_cessation_db}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DBMS_USERNAME:root}
spring.datasource.password=${DBMS_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect